/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data.nim;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class FormMahasiswa extends javax.swing.JFrame {
//1. MEMBUAT VARIABLE
    // VARIABLE INPUTAN 
    private String nama;
    private String nim;
     private String jurusan;
     private String jenis_kelamin;
     private String ukm;
    //variable output 
    private String output; 
    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTNAMA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTNIM = new javax.swing.JTextField();
        BTNTAMPIL = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        J1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        LK = new javax.swing.JRadioButton();
        PR = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        f1 = new javax.swing.JCheckBox();
        b1 = new javax.swing.JCheckBox();
        m1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM MAHASISWA SAINTEK");

        jLabel2.setText("NAMA      :");

        jLabel3.setText("NIM          :");

        BTNTAMPIL.setText("TAMPILKAN");
        BTNTAMPIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTAMPILActionPerformed(evt);
            }
        });

        jLabel4.setText("JURUSAN :");

        J1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEKNIK INFORMATIKA", "TEKNIK INDUSTRI", "SISTEM INFORMASI", "MATEMATIKA", "TEKNIK ELEKTRO" }));

        jLabel5.setText("JENIS KELAMIN :");

        buttonGroup1.add(LK);
        LK.setText("LAKI - LAKI");

        buttonGroup1.add(PR);
        PR.setText("PEREMPUAN");

        jLabel6.setText("UKM :");

        f1.setText("Futsal");

        b1.setText("Basket");

        m1.setText("Musik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m1)
                    .addComponent(b1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(LK)
                    .addComponent(PR)
                    .addComponent(jLabel6)
                    .addComponent(f1)
                    .addComponent(BTNTAMPIL, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNTAMPIL)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNTAMPILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTAMPILActionPerformed
        // 2. mengambil nilai dari inputtan
      
        nama = TXTNAMA.getText();
        nim = TXTNIM.getText();
        jurusan = J1.getSelectedItem().toString();
        if (LK.isSelected()){
            jenis_kelamin = LK.getText();
        } else if (PR.isSelected()){
            jenis_kelamin = PR.getText();
        } else {
            jenis_kelamin = "Tidak Valid !";
        }
        ukm = "";
        if(f1.isSelected()){
            ukm ="-"+ f1.getText();
        }
        if(b1.isSelected()){
            ukm +="-"+b1.getText();
        }
        if(m1.isSelected()){
            ukm +="-"+ m1.getText();
        }
            
        
        
        output = "Nama Mahasiswa = "+nama+"\n";
        output += "NIM = "+nim+"\n";
        output += "Jurusan = "+jurusan +"\n";
        output += "Jenis Kelamin = "+jenis_kelamin+"\n";
        output += " UKM ="+ukm+"\n";
        
        
        JOptionPane.showMessageDialog(null,output);
    }//GEN-LAST:event_BTNTAMPILActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNTAMPIL;
    private javax.swing.JComboBox<String> J1;
    private javax.swing.JRadioButton LK;
    private javax.swing.JRadioButton PR;
    private javax.swing.JTextField TXTNAMA;
    private javax.swing.JTextField TXTNIM;
    private javax.swing.JCheckBox b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox f1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox m1;
    // End of variables declaration//GEN-END:variables
}
